spring:
  application:
    name: catchme

  datasource:
    url: jdbc:h2:mem:${H2_DB_NAME}
    driver-class-name: org.h2.Driver
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update   # 초기 개발용
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: ${SERVER_PORT}

  jwt:
    issuer: ${JWT_ISSUER}
    secret-key: ${JWT_SECRET_KEY}
